version: "3.8"
services:
  db:
    container_name: shortener-db
    image: postgres:13.3-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"

  redis:
    container_name: shortener-redis
    image: redis:6.2.4-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    environment:
      - PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"

  server:
    container_name: server-go-shortener
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - db
      - redis
    command: ["/app/main"]

volumes:
  db-data:
    driver: local
